### ISSUE TITLE
Test passing but seet throwing error

### ISSUE THREAD

**Issue by pavanfhw** [fonoster/seet#3]
I'm running my test with an UAC and a UAS. The messages logs for both user agents generated by the test are as expected by the scenarios defined. 
The output show that the scenario passed but also that the code thrown an error:

```
 SEET Test Plan / 1 scenario(s) found
    ✔ Basic Sipstone UAC


  1 passing (22s)

/usr/local/lib/node_modules/@fonoster/seet/node_modules/mocha/lib/runner.js:962
    throw err;
    ^

Error: done() called multiple times in test <SEET Test Plan / 1 scenario(s) found Basic Sipstone UAC> of file /usr/local/lib/node_modules/@fonoster/seet/dist/src/seet.js; in addition, done() received error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/@fonoster/seet/dist/src/agent.js:71:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    at createMultipleDoneError (/usr/local/lib/node_modules/@fonoster/seet/node_modules/mocha/lib/errors.js:428:13)
    at multiple (/usr/local/lib/node_modules/@fonoster/seet/node_modules/mocha/lib/runnable.js:290:24)
    at done (/usr/local/lib/node_modules/@fonoster/seet/node_modules/mocha/lib/runnable.js:301:14)
    at /usr/local/lib/node_modules/@fonoster/seet/node_modules/mocha/lib/runnable.js:396:16
    at Timeout._onTimeout (/usr/local/lib/node_modules/@fonoster/seet/dist/src/agent.js:71:13)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ERR_MOCHA_MULTIPLE_DONE',
  valueType: 'object',
  value: Error: timeout
      at Timeout._onTimeout (/usr/local/lib/node_modules/@fonoster/seet/dist/src/agent.js:71:18)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
}
```

What does this error mean? How can I debug this if there are no error.log files generated?

**Comment by psanders** [comment]
Can you share the pcap? Also which version are you using? Are you launching seet with docker?

**Comment by psanders** [comment]
@pavanfhw can you share your `seet.json` file?

**Comment by psanders** [comment]
@pavanfhw I am going to close this for now to keep things clean. If you encounter this issue again, please attach supporting files.
